name: Build to Cloudflare Pages

permissions: write-all

on:
    pull_request:
        types: [opened, synchronize]

env:
    NODE_OPTIONS: '--max-old-space-size=8192'
    CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
    CLOUDFLARE_ACCOUNT_ID: ${{ secrets.ACCOUNT_ID }}

jobs:
    build_to_cloudflare_pages:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout to repo
              uses: actions/checkout@v3

            - name: Setup node
              uses: actions/setup-node@v2

            - name: Get cached artifact
              uses: actions/cache@v3
              with:
                  key: gatsby-public-folder
                  path: public

            - name: Install dependencies
              run: npm ci

            - name: Build project
              run: npm run build:incremental

            - name: Publish to Cloudflare Pages
              id: publish_to_pages
              run: |
                  echo "Installing Wrangler CLI"
                  npm i -g wrangler

                  echo "Deploying build to Cloudflare Pages"
                  directory='public'
                  projectName='deriv-com-playground'
                  branch=$GITHUB_HEAD_REF
                  preview_url=$(wrangler pages deploy $directory --project-name=$projectName --branch=$branch | grep -o 'https://[^\"]*.pages.dev')

                  echo "Retrieving preview URL"
                  echo "preview_url=$preview_url" >> "$GITHUB_OUTPUT"

            - name: Retrieve Cloudflare Pages Preview URL
              id: vercel_preview_url
              uses: actions/github-script@v3
              with:
                  script: |
                      const preview_url = '${{ steps.publish_to_pages.outputs.preview_url }}'

                      const comment = [
                        '| Name | Result |',
                        '| :--- | :------ |',
                        `| **Preview URL**  | [Visit Preview](${preview_url}) |`,
                        ''
                      ].join('\n')
                      core.setOutput("comment", comment);

            - name: Post Cloudflare Pages Preview comment
              uses: marocchino/sticky-pull-request-comment@v2
              with:
                  header: Vercel Preview Comment
                  number: ${{github.event.issue.number}}
                  message: ${{steps.vercel_preview_url.outputs.comment}}
