name: Invalidate master cache

permissions: write-all

on:
    push:
        branches:
            - 'master'
            
env:
    NODE_OPTIONS: '--max-old-space-size=8192'

concurrency:
    group: invalidate-master-cache
    cancel-in-progress: true

jobs:
    validate-master-cache:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout to repo
              uses: actions/checkout@v3

            - name: Setup node
              uses: actions/setup-node@v2

            - name: Get master cache
              uses: actions/cache/restore@v3
              with:
                  key: master-cache-public
                  path: |
                      .cache
                      public

            - name: Get cached dependencies
              id: cache-npm
              uses: actions/cache/restore@v3
              with:
                  path: node_modules
                  key: master-npm-${{ hashFiles('**/package-lock.json') }}

            - name: Install dependencies
              if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
              run: npm ci

            - name: Save cached dependencies
              if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
              uses: actions/cache/save@v3
              with:
                  path: node_modules
                  key: master-npm-${{ hashFiles('**/package-lock.json') }}

            - name: Rebuild master cache
              run: npm run build

            - name: Save master cache
              uses: actions/cache/save@v3
              with:
                  key: master-cache-public
                  path: |
                    .cache
                    public

