name: Invalidate master cache

permissions: write-all

on:
    schedule:
      - cron: '0 4 * * *'
    workflow_dispatch:

env:
    NODE_OPTIONS: '--max-old-space-size=8192'

concurrency:
    group: invalidate-master-cache
    cancel-in-progress: true

jobs:
    validate-master-cache:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout to repo
              uses: actions/checkout@v3

            - name: Setup node
              uses: actions/setup-node@v2

            - name: Get master cache
              id: restore_master_cache
              uses: actions/cache/restore@v3
              with:
                  key: master-cache-public
                  path: |
                      .cache
                      public

            - name: Get dependencies key
              id: dependency_key
              run: |
                  echo "dependency_key=npm-${{ hashFiles('**/package-lock.json') }}" > "$GITHUB_OUTPUT"
    
            - name: Get cached dependencies
              id: cache-npm
              uses: actions/cache/restore@v3
              with:
                  path: node_modules
                  key: ${{ steps.dependency_key.outputs.dependency_key }}

            - name: Install dependencies
              if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
              run: npm ci

            - name: Save cached dependencies
              if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
              uses: actions/cache/save@v3
              with:
                  key: ${{ steps.dependency_key.outputs.dependency_key }}
                  path: node_modules

            - name: Rebuild master cache
              id: build_cache
              run: npm run build

            - name: Save master cache
              if: ${{ always() && steps.build_cache.outcome == 'success' }}
              uses: actions/cache/save@v3
              with:
                  key: master-cache-public
                  path: |
                      .cache
                      public

            # - name: Backup master cache
            #   if: ${{ always() && steps.build_cache.outcome == 'success' }}
            #   uses: actions/cache/save@v3
            #   with:
            #       key: master-cache-public-replica
            #       path: |
            #           .cache
            #           public
                      
            # - name: Clear master cache on build failure
            #   if: ${{ (failure() || cancelled()) && steps.restore_master_cache.outputs.cache-hit == 'true' }}
            #   run: |
            #       owner="adrienne-deriv"
            #       repo="deriv-com-playground"
            #       cache_key="${{ steps.restore_master_cache.outputs.cache-matched-key }}"
            #       curl \
            #         -X DELETE \
            #         -H "Accept: application/vnd.github.v3+json" \
            #         -H "Authorization: token ${{ github.token }}" \
            #         https://api.github.com/repos/$owner/$repo/actions/caches?key=$cache_key
